/// Flutter icons PyramidIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PyramidIcon
///      fonts:
///       - asset: fonts/PyramidIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PyramidIcon {
  PyramidIcon._();

  static const _kFontFam = 'PyramidIcon';
  static const String _kFontPkg = null;

  static const IconData noun_pyramid_1040358 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
